modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/Hydroline/hydroline-beacon-provider/issues"
showAsResourcePack=false

[[mods]]
modId="beaconprovider"
version="${version}"
displayName="Hydroline Beacon Provider"
updateJSONURL=""
displayURL="https://github.com/Hydroline/hydroline-beacon-provider"
credits=""
authors="Hydroline"
description='''
Bridge mod entrypoint for Hydroline Beacon Provider on Forge.
'''

[[dependencies.beaconprovider]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.beaconprovider]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,1.18.3)"
ordering="NONE"
side="BOTH"
