modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/Hydroline/hydroline-beacon-provider/issues"
showAsResourcePack=false

[[mods]]
modId="beaconprovider"
version="${version}"
displayName="Hydroline Beacon Provider"
updateJSONURL=""
displayURL="https://github.com/Hydroline/hydroline-beacon-provider"
credits=""
authors="Hydroline"
description='''
Bridge mod entrypoint for Hydroline Beacon Provider on Forge.
'''

[[dependencies.beaconprovider]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.beaconprovider]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.16.6)"
ordering="NONE"
side="BOTH"
